services:
  - type: web
    name: fidelity-backend
    env: node
    region: frankfurt
    buildCommand: npm install
    startCommand: ./start.sh
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_SHEET_ID
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_EMAIL
        sync: false
      - key: GOOGLE_PRIVATE_KEY
        sync: false 